/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTriviaIndexRouteImport } from './routes/_admin/trivia/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminTriviaGamesGameIdRouteImport } from './routes/_admin/trivia/games/$gameId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTriviaIndexRoute = AdminTriviaIndexRouteImport.update({
  id: '/trivia/',
  path: '/trivia/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTriviaGamesGameIdRoute = AdminTriviaGamesGameIdRouteImport.update({
  id: '/trivia/games/$gameId',
  path: '/trivia/games/$gameId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/trivia/': typeof AdminTriviaIndexRoute
  '/trivia/games/$gameId': typeof AdminTriviaGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/trivia': typeof AdminTriviaIndexRoute
  '/trivia/games/$gameId': typeof AdminTriviaGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/trivia/': typeof AdminTriviaIndexRoute
  '/_admin/trivia/games/$gameId': typeof AdminTriviaGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/trivia/'
    | '/trivia/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/auth/$' | '/trivia' | '/trivia/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/api/auth/$'
    | '/_admin/trivia/'
    | '/_admin/trivia/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/trivia/': {
      id: '/_admin/trivia/'
      path: '/trivia'
      fullPath: '/trivia/'
      preLoaderRoute: typeof AdminTriviaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/trivia/games/$gameId': {
      id: '/_admin/trivia/games/$gameId'
      path: '/trivia/games/$gameId'
      fullPath: '/trivia/games/$gameId'
      preLoaderRoute: typeof AdminTriviaGamesGameIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTriviaIndexRoute: typeof AdminTriviaIndexRoute
  AdminTriviaGamesGameIdRoute: typeof AdminTriviaGamesGameIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTriviaIndexRoute: AdminTriviaIndexRoute,
  AdminTriviaGamesGameIdRoute: AdminTriviaGamesGameIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
