/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as DashboardAppRouteImport } from './routes/_dashboard/_app'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardAppIndexRouteImport } from './routes/_dashboard/_app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminTriviaIndexRouteImport } from './routes/_dashboard/admin/trivia/index'
import { Route as DashboardAppGamesGameIdRouteImport } from './routes/_dashboard/_app/games/$gameId'
import { Route as DashboardAdminTriviaGamesGameIdRouteImport } from './routes/_dashboard/admin/trivia/games/$gameId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppRoute = DashboardAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAppIndexRoute = DashboardAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminTriviaIndexRoute =
  DashboardAdminTriviaIndexRouteImport.update({
    id: '/trivia/',
    path: '/trivia/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAppGamesGameIdRoute = DashboardAppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => DashboardAppRoute,
} as any)
const DashboardAdminTriviaGamesGameIdRoute =
  DashboardAdminTriviaGamesGameIdRouteImport.update({
    id: '/trivia/games/$gameId',
    path: '/trivia/games/$gameId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardAppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/games/$gameId': typeof DashboardAppGamesGameIdRoute
  '/admin/trivia/': typeof DashboardAdminTriviaIndexRoute
  '/admin/trivia/games/$gameId': typeof DashboardAdminTriviaGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardAppIndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/games/$gameId': typeof DashboardAppGamesGameIdRoute
  '/admin/trivia': typeof DashboardAdminTriviaIndexRoute
  '/admin/trivia/games/$gameId': typeof DashboardAdminTriviaGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/_app': typeof DashboardAppRouteWithChildren
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/_app/': typeof DashboardAppIndexRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/_app/games/$gameId': typeof DashboardAppGamesGameIdRoute
  '/_dashboard/admin/trivia/': typeof DashboardAdminTriviaIndexRoute
  '/_dashboard/admin/trivia/games/$gameId': typeof DashboardAdminTriviaGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/api/auth/$'
    | '/admin/'
    | '/games/$gameId'
    | '/admin/trivia/'
    | '/admin/trivia/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/admin'
    | '/games/$gameId'
    | '/admin/trivia'
    | '/admin/trivia/games/$gameId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/_app'
    | '/_dashboard/admin'
    | '/api/auth/$'
    | '/_dashboard/_app/'
    | '/_dashboard/admin/'
    | '/_dashboard/_app/games/$gameId'
    | '/_dashboard/admin/trivia/'
    | '/_dashboard/admin/trivia/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_app': {
      id: '/_dashboard/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardAppRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/_app/': {
      id: '/_dashboard/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardAppIndexRouteImport
      parentRoute: typeof DashboardAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/trivia/': {
      id: '/_dashboard/admin/trivia/'
      path: '/trivia'
      fullPath: '/admin/trivia/'
      preLoaderRoute: typeof DashboardAdminTriviaIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/_app/games/$gameId': {
      id: '/_dashboard/_app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof DashboardAppGamesGameIdRouteImport
      parentRoute: typeof DashboardAppRoute
    }
    '/_dashboard/admin/trivia/games/$gameId': {
      id: '/_dashboard/admin/trivia/games/$gameId'
      path: '/trivia/games/$gameId'
      fullPath: '/admin/trivia/games/$gameId'
      preLoaderRoute: typeof DashboardAdminTriviaGamesGameIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAppRouteChildren {
  DashboardAppIndexRoute: typeof DashboardAppIndexRoute
  DashboardAppGamesGameIdRoute: typeof DashboardAppGamesGameIdRoute
}

const DashboardAppRouteChildren: DashboardAppRouteChildren = {
  DashboardAppIndexRoute: DashboardAppIndexRoute,
  DashboardAppGamesGameIdRoute: DashboardAppGamesGameIdRoute,
}

const DashboardAppRouteWithChildren = DashboardAppRoute._addFileChildren(
  DashboardAppRouteChildren,
)

interface DashboardAdminRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminTriviaIndexRoute: typeof DashboardAdminTriviaIndexRoute
  DashboardAdminTriviaGamesGameIdRoute: typeof DashboardAdminTriviaGamesGameIdRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminTriviaIndexRoute: DashboardAdminTriviaIndexRoute,
  DashboardAdminTriviaGamesGameIdRoute: DashboardAdminTriviaGamesGameIdRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAppRoute: typeof DashboardAppRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppRoute: DashboardAppRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
